/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sintactic;

import sintactic.controllers.Lexico;

public class App {

    public static void main(String[] args) {
        Lexico lexico = new Lexico();
        lexico.analyze();
        lexico.printTokensTable();
    }
}
